"""
test_allocator.py — Layer 2 Allocator Agent
============================================================
Run with:  python test_allocator.py

Uses:
- REAL Gemini calls
- REAL allocator behavior
- Optional real Supabase inventory
"""

from __future__ import annotations
from dotenv import load_dotenv
load_dotenv()

import json
import logging
import os
import unittest
from unittest.mock import patch


# ── Logging ──────────────────────────────────────────────────────────────────

logging.basicConfig(
    level=logging.INFO,
    format="%(message)s",
)

logging.getLogger("httpx").setLevel(logging.WARNING)
logging.getLogger("httpcore").setLevel(logging.WARNING)

logger = logging.getLogger("test_allocator")


# ── Context packets ──────────────────────────────────────────────────────────

FLOOD_CONTEXT_PACKET = {
    "incident_id": "INC-2024-FLOOD-001",
    "incident": {
        "type": "flood",
        "location": "Patna, Bihar",
        "severity": "high",
    },
    "needs_summary": (
        "Approx. 15,000 people stranded across 6 villages in the Patna district. "
        "Roads NH-30 and NH-31 are submerged. Drinking water supply cut off. "
        "Rising risk of waterborne diseases. 3 villages accessible only by helicopter."
    ),
    "map_description": (
        "Villages Rampur, Sitapur, and Narayanpur are 8-12 km east of Patna city. "
        "NH-30 flooded near Fatuha bridge. Helicopter landing zones available at "
        "Rampur school ground and Narayanpur grain store rooftop."
    ),
}

FLOOD_DELTA_PACKET = {
    "incident_id": "INC-2024-FLOOD-001",
    "incident": {
        "type": "flood",
        "location": "Patna, Bihar",
        "severity": "critical",
    },
    "needs_summary": (
        "Update: 5 additional villages now submerged. Total affected ~22,000 people. "
        "New need: trauma kits for 80 injured rescued from collapsed buildings."
    ),
    "map_description": (
        "New villages: Jhalwa, Bihta, Khagaul. "
        "NH-139 remains accessible."
    ),
}


# ── Helpers ──────────────────────────────────────────────────────────────────

def _pretty(obj: object) -> str:
    return json.dumps(obj, indent=2, default=str)


def _allocation_summary(result: dict) -> list[dict]:
    return [
        {
            "item": a.get("item"),
            "qty": a.get("quantity"),
            "status": a.get("status"),
        }
        for a in result["allocations"]
    ]


def _run_agent(packet: dict):
    from allocator_agent import run_allocator_agent
    return run_allocator_agent(packet)


# ── Test cases ───────────────────────────────────────────────────────────────

class TestAllocatorAgent(unittest.TestCase):

    # ── Scenario A ───────────────────────────────────────────────────────────

    @patch("allocator_agent.deduct_inventory", return_value=True)
    def test_a_normal_flood_allocation(
        self,
        mock_deduct,
    ):
        logger.info("\n[Scenario A] Normal flood allocation")

        result = _run_agent(FLOOD_CONTEXT_PACKET)

        logger.info(
            "Allocations: %s",
            _allocation_summary(result)
        )

        self.assertEqual(
            result["incident_id"],
            "INC-2024-FLOOD-001"
        )

        self.assertGreater(
            len(result["allocations"]),
            0
        )

        logger.info("✓ Scenario A passed")

    # ── Scenario B ───────────────────────────────────────────────────────────

    @patch("allocator_agent.deduct_inventory", return_value=True)
    def test_b_delta_allocation(
        self,
        mock_deduct,
    ):
        logger.info("\n[Scenario B] Delta allocation")

        result = _run_agent(FLOOD_DELTA_PACKET)

        logger.info(
            "Allocations: %s",
            _allocation_summary(result)
        )

        self.assertEqual(
            result["incident_id"],
            "INC-2024-FLOOD-001"
        )

        self.assertGreater(
            len(result["allocations"]),
            0
        )

        logger.info("✓ Scenario B passed")

    # ── Scenario C ───────────────────────────────────────────────────────────

    @patch("allocator_agent.deduct_inventory", return_value=True)
    def test_c_admin_approval(
        self,
        mock_deduct,
    ):
        logger.info("\n[Scenario C] Admin approval flow")

        result = _run_agent(FLOOD_CONTEXT_PACKET)

        pending = [
            a for a in result["allocations"]
            if a["status"] == "pending_approval"
        ]

        if not pending:
            logger.warning(
                "No pending approvals generated by Gemini."
            )
            return

        approval_id = pending[0]["approval_id"]

        logger.info(
            "Pending approval_id: %s",
            approval_id,
        )

        from allocator_agent import approve_and_execute

        approved_result = approve_and_execute(
            approval_id
        )

        logger.info(
            "Approved allocation: %s",
            _allocation_summary(approved_result)
        )

        self.assertIsNotNone(
            approved_result
        )

        logger.info("✓ Scenario C passed")


# ── Live smoke test ──────────────────────────────────────────────────────────

def live_smoke_test():

    required = [
        "SUPABASE_URL",
        "SUPABASE_SERVICE_ROLE_KEY",
        "GEMINI_API_KEY",
    ]

    if not all(os.getenv(k) for k in required):
        logger.warning(
            "Skipping live smoke test — env vars not set."
        )
        return

    logger.info("\n[Live Smoke Test]")

    from allocator_agent import run_allocator_agent

    result = run_allocator_agent(
        FLOOD_CONTEXT_PACKET
    )

    logger.info(
        "Live allocations: %s",
        _allocation_summary(result)
    )


# ── Entry point ──────────────────────────────────────────────────────────────

if __name__ == "__main__":

    unittest.main(
        verbosity=1,
        exit=False,
    )

    RUN_LIVE_TEST = False

    if RUN_LIVE_TEST:
        live_smoke_test()